name: B9 - Deployment on EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub repo
        uses: actions/checkout@v4

      - name: Run some commands
        run: |
          whoami
          ls -al
          pwd
          cat index.html

      - name: Copy code to EC2 server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: ./
          target: /home/ubuntu

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo cp -r ./ /var/www/html
